### PR TITLE
SparkTracks: More consistent description style

### PR DESCRIPTION
**Pull request by McMistrzYT**

### CODE REVIEW

**Comment by LeleDerGrasshalmi** [comment]
they are ordered like that on purpose, like its in the actual api.

**Comment by McMistrzYT** [comment]
i can revert the order then and keep the new descriptions

**Comment by LeleDerGrasshalmi** [comment]
Hi @McMistrzYT, why can you not?
Just make a new commit

**Comment by McMistrzYT** [comment]
yea i forgor wait

**Comment by McMistrzYT** [comment]
all done

**Review by LeleDerGrasshalmi — APPROVED** [review]
looks good ig, sorry for the late response

**Comment by nyny21** [comment]
I can't get on

**Comment by LeleDerGrasshalmi** [comment]
What?

**Pull request merged**
