### PR TITLE
Update ExchangeGameCurrencyForBattlePassOffer.md

### PR DESCRIPTION
**Pull request by Krowe-moh**
no infomation about it currently

### CODE REVIEW

**Review by LeleDerGrasshalmi — CHANGES_REQUESTED** [review]
please fix formatting

**Comment by Krowe-moh** [comment]
done 👍

**Review by LeleDerGrasshalmi — CHANGES_REQUESTED** [review]
still broken/weird formatted

use https://beautifier.io

**Review by LeleDerGrasshalmi — APPROVED** [review]
good

**Pull request merged**
