### PR TITLE
Add the new SetActiveArchetype operation added in v30.00

### PR DESCRIPTION
**Pull request by PRO100KatYT**
At the moment the only use for this operation I am aware of is to set the Primary Vehicle in the Locker.

### CODE REVIEW

**Comment by PRO100KatYT** [comment]
Something like this? Currently the only loadout with an ArchetypeGroupTag in their properties is the vehicles one.

**Comment by LeleDerGrasshalmi** [comment]
alr, could you please move it to the new fn service dir`?

**Comment by PRO100KatYT** [comment]
Done

**Comment by LeleDerGrasshalmi** [comment]
alright, LGTM

**Pull request merged**
