### PR TITLE
Create RecordCampaignMatchEnded mcp operation

### PR DESCRIPTION
**Pull request by MazieK0nk**
New MCP operation

### CODE REVIEW

**Comment by LeleDerGrasshalmi** [comment]
change description in the pr template exists for a reason actually

**Comment by Krowe-moh** [comment]
description incorrect because the mcp doesn't accept campaign profile

**Comment by LeleDerGrasshalmi** [comment]
@MazieK0nk please perform the requested changes within the next 2 weeks or im going to close this PR as stale.

**Comment by LeleDerGrasshalmi** [comment]
ok

**Comment by LeleDerGrasshalmi** [comment]
@MazieK0nk could you please make a new PR with the new fn service location?

**Pull request merged**
