### PR TITLE
Create DepositPostResources

### PR DESCRIPTION
**Pull request by pippococaina**
added DepositPostResources operation

### CODE REVIEW

**Review by LeleDerGrasshalmi — CHANGES_REQUESTED** [review]
You forgot the file extension, it should me a markdown `.md` file.

**Comment by pippococaina** [comment]
Done

**Review by LeleDerGrasshalmi — CHANGES_REQUESTED** [review]
Formatting is incomplete:

image

You are missing a newline:
```
**Description**: `Transfer items from backpack to deposit` \
**Profiles**: `theater0` \
**Note**: `DedicatedServer ONLY`
```

**Review by LeleDerGrasshalmi — APPROVED** [review]
LGTM

**Pull request merged**
